In [8]:
import sys
import numpy as np
import pandas as pd
import os
import warnings
warnings.filterwarnings('ignore')

In [9]:
def read_data(data_file, DATA_PATH):
    df = pd.read_excel( os.path.join(DATA_PATH, data_file) )
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.set_index('Date') 
    df = df.loc['12/31/2001':,]
    
    return df

In [11]:
data_file = 'BCOMTR.xlsx'
DATA_PATH = "./data"
data = read_data(data_file, DATA_PATH)
data = data.rename(columns={"PX_LAST": "BCOMTR"})

In [13]:
indexes = np.array(['LBUSTRUU', 'LG30TRUU', 'LMBITR', 'NDDUE15X', 'NDDUJN', 'NDDUNA', 'NDDUPXJ', 
                    'NDDUUK', 'NDDUWXUS', 'NDUEEGF', 'RU10GRTR', 'RU10VATR', 'RU20GRTR', 'RU20INTR', 'RU20VATR',
                    'RUMCINTR', 'RUMRINTR', 'RUTPINTR', 'S5COND', 'S5CONS', 'S5ENRS', 'S5FINL', 'S5HLTH',
                    'S5INDU', 'S5INFT', 'S5MATR', 'S5RLST', 'S5TELS', 'S5UTIL', 'SPXT'])

for i in indexes:
    
    data_file = i+'.xlsx'
    DATA_PATH = "./data"
    df = read_data(data_file, DATA_PATH)
    
    data.insert(0, i, df['PX_LAST'], True)

In [14]:
data

,SPXT,S5UTIL,S5TELS,S5RLST,S5MATR,S5INFT,S5INDU,S5HLTH,S5FINL,S5ENRS,...,NDDUWXUS,NDDUUK,NDDUPXJ,NDDUNA,NDDUJN,NDDUE15X,LMBITR,LG30TRUU,LBUSTRUU,BCOMTR
Date,,,,,,,,,,,,,,,,,,,,,
2001-12-31,1618.98,145.88,168.11,97.15,132.93,352.70,265.77,385.59,355.26,211.30,...,2218.279,2786.917,1308.071,2546.608,2653.436,2468.485,558.0707,317.5810,1009.27,148.8430
2002-01-02,1628.51,147.80,171.43,97.43,133.16,363.03,266.09,384.28,354.15,211.01,...,2216.814,2768.599,1315.016,2562.579,2632.147,2481.602,558.6473,318.9528,1004.79,150.2790
2002-01-03,1643.48,146.47,173.74,98.16,135.32,381.59,265.82,381.10,356.07,210.05,...,2242.870,2814.072,1316.369,2588.863,2640.642,2515.214,559.9075,320.0004,1007.13,149.8550
2002-01-04,1653.69,145.85,172.57,97.58,138.32,384.57,268.28,380.44,361.18,211.43,...,2253.044,2817.015,1339.246,2605.910,2716.067,2501.221,560.0128,320.6761,1006.82,152.9060
2002-01-07,1642.95,146.92,171.03,97.37,138.22,380.21,263.92,378.81,358.61,210.65,...,2237.384,2792.434,1354.581,2589.637,2716.053,2469.080,561.0722,321.8279,1012.11,154.4580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-05-18,6037.90,288.82,175.85,201.21,334.75,1682.71,534.90,1178.58,367.15,292.87,...,5232.426,5100.222,5333.833,8477.945,5911.836,5827.238,1272.5350,1273.0070,2325.90,134.4572
2020-05-19,5975.15,283.92,175.13,197.48,331.40,1675.91,528.03,1164.35,357.89,284.40,...,5279.920,5083.848,5480.551,8405.295,5996.649,5841.331,1274.6720,1279.7800,2331.45,134.9047
2020-05-20,6075.76,285.33,179.85,199.16,336.79,1711.36,537.56,1165.78,365.83,295.26,...,5339.742,5146.560,5493.737,8543.667,6055.935,5927.015,1278.1700,1290.2810,2339.13,135.6881
2020-05-21,6028.93,282.46,179.04,198.09,333.44,1687.43,538.45,1156.32,364.54,290.88,...,5284.146,5083.175,5445.707,8478.019,6016.737,5855.667,1281.4880,1295.5110,2340.13,134.4284
2020-05-22,6044.16,285.67,179.85,202.46,332.86,1694.51,537.84,1158.51,363.60,288.94,...,5239.394,5051.782,5261.542,8499.796,5980.843,5825.021,1284.6110,1294.1250,2341.41,133.8446

In [15]:
data.to_csv('data.csv', index=False)